# Generated by Django 5.2.1 on 2025-05-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='posted_by',
            field=models.CharField(max_length=100),
        ),
    ]
