# Generated by Django 5.2.1 on 2025-06-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sight',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
